export const language = {
    en: {
        pizzaFormProject: "In the Pizza Form Project, I created a Homepage, Order Form and Order Received page for the Teknolojik Yemekler brand, a website designed to bring food to hungry software developers sitting in front of their computers. I worked on React, Axios and Form Elements.",
        pizzaFormProjectHeading: "Pizza Form Project",
        projets: "Projects",
        footerHeading: "Let's work together on your next product.",
        personalBlog: "Personal Blog",
        profile: "Profile",
        aboutme: "About Me",
        aboutmep1: "I am an aspiring full-stack developer with a growth mindset to acquire new skills and continuously develop myself with new challenges.",
        aboutmep2: "After I graduated from university, I decided to fulfill my childhood dream  to become a  software developer and improve myself in front end, back end and CS by completing a 6-month intensive Workintech full-stack development program.",
        nodejs: "Node.js® is a free, open-source, cross-platform JavaScript runtime environment that lets developers create servers, web apps, command line tools and scripts.",
        react: "React is a library. It lets you put components together, but it doesn’t prescribe how to do routing and data fetching. React lets you build user interfaces out of individual pieces called components.",
        javascript: "JavaScript is one of the most popular programming languages in the world. JavaScript allows you to implement complex features on web pages.",
        light: "LIGHT",
        dark: "DARK",
        mode: "MODE",
        skills: "Skills",
        projects: "Projects",
        hireMe: "Hire me",
        heroHeading: "Creative thinker Minimalism lover",
        heroSelf: "Hi, I'm Berk. I'm a full-stack developer. If you are looking for a Developer who to craft solid and scalable frontend products with great user experiences. Let's shake hands with me."
    },
    tr: {
        pizzaFormProject: "Pizza Form Projesinde, bilgisayar başında karnı acıkan yazılımcılara yiyecek getirmek için tasarlanmış bir web sitesi Teknolojik Yemekler markasına, Anasayfa, Sipariş Formu ve Sipariş Alındı sayfası oluşturdum. React, Axios ve Form Elemanları için çalıştım.",
        pizzaFormProjectHeading: "Pizza Form Projesi",
        projets: "Projeler",
        footerHeading: "Sıradaki projede birlikte çalışalım.",
        personalBlog: "Kişisel Blog",
        profile: "Profil",
        aboutme: "Hakkımda",
        aboutmep1: "Yeni beceriler edinmek ve kendimi sürekli olarak yeni zorluklarla geliştirmek için kendini sürekli geliştirme mentalitesine sahip, hevesli bir full-stack yazılım geliştiricisiyim.",
        aboutmep2: "Üniversiteden mezun olduktan sonra, 6 aylık yoğun bir Workintech full-stack geliştirme programını tamamlayarak bir yazılım geliştiricisi olmaya ve kendimi frontend, backend ve CS'de geliştirmeye ve bu sayede çocukluk hayalimi gerçekleştirmeye karar verdim.",
        nodejs: "Node.js®, geliştiricilerin sunucular, web uygulamaları, komut satırı araçları ve scriptler oluşturmasına olanak tanıyan ücretsiz, açık kaynaklı, platformlar arası bir JavaScript çalıştırma ortamıdır.",
        react: "React bir kütüphanedir. Bileşenleri bir araya getirmenize olanak sağlar, ancak yönlendirme ve veri çekme gibi konularda nasıl yapılacağına dair talimat vermez. React, bileşen adı verilen birbirinden ayrı parçalardan kullanıcı arayüzü oluşturmanızı sağlar.",
        javascript: "JavaScript dünyadaki en popüler programlama dillerinden biridir. JavaScript, web sayfalarında karmaşık özellikler uygulamanıza olanak tanır.",
        light: "AYDINLIK",
        dark: "KARANLIK",
        mode: "MOD",
        skills: "Yetenekler",
        projects: "Projeler",
        hireMe: "Beni işe al",
        heroHeading: "Yaratıcı düşünür Minimalizm sever",
        heroSelf: "Merhaba, ben Berk. Full-stack bir geliştiriciyim. Harika kullanıcı deneyimlerine sahip, sağlam ve ölçeklenebilir frontend ürünleri tasarlayacak bir Geliştirici arıyorsanız. Hadi el sıkışalım."
    }
}